Two way patch streaming

diff --git a/gito-listen b/gito-listen
--- a/gito-listen
+++ b/gito-listen
@@ -11,14 +11,14 @@ while test "$1"; do
   case "$1" in
     #-a|--autosync)
     #  autosync_mode=1;shift;;
-    -*)
-      die "$1 is not an option";;
+    -p|--push) push=1;shift;;
+    -*) die "$1 is not an option";;
   esac
 done
 
-REMOTE="${1-`git remote get-url origin`}"
+REMOTE="$(git remote get-url origin)"
 SSH_HOST="${REMOTE%%:*}"
-REMOTE_PATH="${REMOTE#*:}"
+REMOTE_FILE="${REMOTE#*:}"
 
 autosync() {
   ( cd "$GIT_WORK_TREE"
@@ -28,26 +28,45 @@ autosync() {
 
 grep -q : <<<"$REMOTE" && ssh_mode="ssh $SSH_HOST -- "
 
-gito sync -f
-
 # XXX: This will trigger on received messages also
 #test "$autosync_mode" && autosync
 
-$ssh_mode tail -f -n0 "$REMOTE_PATH/pubsub" \
-| while read -r -d '' patch; do
-  hash=$(head -n1 <<<"$patch" | grep -oE " [a-f0-9]{40} ")
+start_push() {
+  info "Pushing"
+  while true; do
+    #tail -f -n0 $PUBSUB_FILE | $ssh_mode tee -a "$REMOTE_FILE/pubsub"
+    echo -n > "$PUBSUB_FILE"
+    tail -f -n0 "$PUBSUB_FILE" | $ssh_mode "$REMOTE_FILE/bare-listen" "$REMOTE_FILE/.." || {
+      warn "Push failed, rebasing"
+      gito sync -f
+    }
+  done
+}
 
-  echo >&2 "=== START PATCH $hash ==="
-  echo >&2 "$patch"
-  echo >&2 "=== END PATCH ==="
+start_pull() {
+  info "Listening"
+  $ssh_mode tail -f -n0 "$REMOTE_FILE/pubsub" | while read -r -d '' patch; do
+    echo >&2 "=== START PULLING PATCH ==="
+    echo >&2 "$patch"
+    echo >&2 "=== END PULLING PATCH ==="
 
-  if git rev-list --quiet -n1 $hash; then
-    echo >&2 "INFO: Patch already applied, skipping"
-  elif git am <<<"$patch"; then
-    echo >&2 "INFO: Applied patch successfully"
-  else
-    git am --abort
-    echo >&2 "INFO: Apply patch failed, rebasing"
-    gito sync -f
-  fi
-done
+    hash=$(head -n1 <<<"$patch" | grep -oE " [a-f0-9]{40} ")
+
+    if git rev-list --quiet -n1 $hash; then
+      echo >&2 "INFO: Patch already applied, skipping"
+    elif git am <<<"$patch"; then
+      echo >&2 "INFO: Applied patch successfully"
+    else
+      git am --abort
+      echo >&2 "INFO: Apply patch failed, rebasing"
+      gito sync -f
+    fi
+  done
+}
+
+gito sync -f
+start_pull &
+if [ "$push" ]; then
+  start_push &
+fi
+wait
